server:
  port: 8010 # ?? ??(???? 8080)
spring:
  profiles:
    active: dev # ????? dev ???? ??
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/basic1__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update # DB ??? ????(??? ???? ??? ?)
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true